<?php
return [
  'ATTACHMENT_PATH' => env('ATTACHMENT_PATH'),
  'ATTACHMENT_UPLOAD' => env('ATTACHMENT_UPLOAD'),
  'NOT_USE_MAIL' => env('NOT_USE_MAIL'),
  'EXEC_PATH' => env('EXEC_PATH'),
  'PYTHON_PATH' => env('PYTHON_PATH'),
  'ISDEMO' => env('ISDEMO'),
  'PYTHON_SERVER' => env('PYTHON_SERVER')
];