<table>
    <tr>
        <td>compcode</td>
        <td>source</td>
        <td>trantype</td>
        <td>auditno</td>
        <td>document</td>
        <td>suppcode</td>
        <td>payto</td>
        <td>suppgroup</td>
        <td>bankcode</td>
        <td>paymode</td>
        <td>cheqno</td>
        <td>cheqdate</td>
        <td>actdate</td>
        <td>recdate</td>
        <td>category</td>
        <td>amount</td>
        <td>outamount</td>
        <td>remarks</td>
        <td>postflag</td>
        <td>doctorflag</td>
        <td>stat</td>
        <td>entryuser</td>
        <td>entrytime</td>
        <td>upduser</td>
        <td>upddate</td>
        <td>conversion</td>
        <td>srcfrom</td>
        <td>srcto</td>
        <td>deptcode</td>
        <td>reconflg</td>
        <td>effectdatefr</td>
        <td>effectdateto</td>
        <td>frequency</td>
        <td>refsource</td>
        <td>reftrantype</td>
        <td>refauditno</td>
        <td>pvno</td>
        <td>SplitCharges</td>
        <td>TaxClaimable</td>
    </tr>
    @foreach ($table as $obj)
        <tr>
            <td>{{$obj->compcode}}</td>
            <td>{{$obj->source}}</td>
            <td>{{$obj->trantype}}</td>
            <td>{{$obj->auditno}}</td>
            <td>{{$obj->document}}</td>
            <td>{{$obj->suppcode}}</td>
            <td>{{$obj->payto}}</td>
            <td>{{$obj->suppgroup}}</td>
            <td>{{$obj->bankcode}}</td>
            <td>{{$obj->paymode}}</td>
            <td>{{$obj->cheqno}}</td>
            <td>{{Carbon\Carbon::parse($obj->cheqdate)->format('d/m/Y')}}</td>
            <td>{{Carbon\Carbon::parse($obj->actdate)->format('d/m/Y')}}</td>
            <td>{{Carbon\Carbon::parse($obj->recdate)->format('d/m/Y')}}</td>
            <td>{{$obj->category}}</td>
            <td>{{$obj->amount}}</td>
            <td>{{$obj->outamount}}</td>
            <td>{{$obj->remarks}}</td>
            <td>@if(empty($obj->postflag)){{'no'}}@else{{'yes'}}@endif</td>
            <td>@if(empty($obj->doctorflag)){{'no'}}@else{{'yes'}}@endif</td>
            <td>{{$obj->stat}}</td>
            <td>{{$obj->entryuser}}</td>
            <td>{{$obj->entrytime}}</td>
            <td>{{$obj->upduser}}</td>
            <td>{{Carbon\Carbon::parse($obj->upddate)->format('d/m/Y')}}</td>
            <td>{{$obj->conversion}}</td>
            <td>{{$obj->srcfrom}}</td>
            <td>{{$obj->srcto}}</td>
            <td>{{$obj->deptcode}}</td>
            <td>no</td>
            <td>{{Carbon\Carbon::parse($obj->effectdatefr)->format('d/m/Y')}}</td>
            <td>{{Carbon\Carbon::parse($obj->effectdateto)->format('d/m/Y')}}</td>
            <td>{{$obj->frequency}}</td>
            <td>{{$obj->refsource}}</td>
            <td>{{$obj->reftrantype}}</td>
            <td>{{$obj->refauditno}}</td>
            <td>{{$obj->pvno}}</td>
            <td>no</td>
            <td>{{$obj->TaxClaimable}}</td>
        </tr>
    @endforeach
</table>