<table>
    <tr>
        <td>idno<td>
        <td>compcode<td>
        <td>source<td>
        <td>trantype<td>
        <td>auditno<td>
        <td>lineno_<td>
        <td>entrydate<td>
        <td>document<td>
        <td>reference<td>
        <td>amount<td>
        <td>stat<td>
        <td>mrn<td>
        <td>episno<td>
        <td>billno<td>
        <td>paymode<td>
        <td>allocauditno<td>
        <td>alloclineno<td>
        <td>alloctnauditno<td>
        <td>alloctnlineno<td>
        <td>lastuser<td>
        <td>lastupdate<td>
        <td>grnno<td>
        <td>dorecno<td>
        <td>category<td>
        <td>deptcode<td>
        <td>adduser<td>
        <td>adddate<td>
        <td>recstatus<td>
        <td>upduser<td>
        <td>upddate<td>
        <td>deluser<td>
        <td>deldate<td>
        <td>GSTCode<td>
        <td>AmtB4GST<td>
        <td>unit<td>
        <td>taxamt<td>
    </tr>
    @foreach ($table as $obj)
        <tr>
            <td>{{$obj->idno}}<td>
            <td>{{$obj->compcode}}<td>
            <td>{{$obj->source}}<td>
            <td>{{$obj->trantype}}<td>
            <td>{{$obj->auditno}}<td>
            <td>{{$obj->lineno_}}<td>
            <td>{{Carbon\Carbon::parse($obj->entrydate)->format('d/m/Y')}}<td>
            <td>{{$obj->document}}<td>
            <td>{{$obj->reference}}<td>
            <td>{{$obj->amount}}<td>
            <td>{{$obj->stat}}<td>
            <td>{{$obj->mrn}}<td>
            <td>{{$obj->episno}}<td>
            <td>{{$obj->billno}}<td>
            <td>{{$obj->paymode}}<td>
            <td>{{$obj->allocauditno}}<td>
            <td>{{$obj->alloclineno}}<td>
            <td>{{$obj->alloctnauditno}}<td>
            <td>{{$obj->alloctnlineno}}<td>
            <td>{{$obj->lastuser}}<td>
            <td>{{Carbon\Carbon::parse($obj->lastupdate)->format('d/m/Y')}}<td>
            <td>{{$obj->grnno}}<td>
            <td>{{$obj->dorecno}}<td>
            <td>{{$obj->category}}<td>
            <td>{{$obj->deptcode}}<td>
            <td>{{$obj->adduser}}<td>
            <td>{{Carbon\Carbon::parse($obj->adddate)->format('d/m/Y')}}<td>
            <td>{{$obj->recstatus}}<td>
            <td>{{$obj->upduser}}<td>
            <td>{{Carbon\Carbon::parse($obj->upddate)->format('d/m/Y')}}<td>
            <td>{{$obj->deluser}}<td>
            <td>{{Carbon\Carbon::parse($obj->deldate)->format('d/m/Y')}}<td>
            <td>{{$obj->GSTCode}}<td>
            <td>{{$obj->AmtB4GST}}<td>
            <td>{{$obj->unit}}<td>
            <td>{{$obj->taxamt}}<td>
        </tr>
    @endforeach
</table>