<table>
    <tr>
        <td>idno</td>
        <td>compcode</td>
        <td>source</td>
        <td>trantype</td>
        <td>auditno</td>
        <td>lineno_</td>
        <td>docsource</td>
        <td>doctrantype</td>
        <td>docauditno</td>
        <td>refsource</td>
        <td>reftrantype</td>
        <td>refauditno</td>
        <td>refamount</td>
        <td>allocdate</td>
        <td>allocamount</td>
        <td>recstatus</td>
        <td>outamount</td>
        <td>paymode</td>
        <td>bankcode</td>
        <td>reference</td>
        <td>cheqdate</td>
        <td>suppcode</td>
        <td>remarks</td>
        <td>lastuser</td>
        <td>lastupdate</td>
        <td>unit</td>
        <td>balance</td>
        <td>can_alloc</td>
    </tr>
    @foreach ($table as $obj)
        <tr>
            <td>{{$obj->idno}}</td>
            <td>{{$obj->compcode}}</td>
            <td>{{$obj->source}}</td>
            <td>{{$obj->trantype}}</td>
            <td>{{$obj->auditno}}</td>
            <td>{{$obj->lineno_}}</td>
            <td>{{$obj->docsource}}</td>
            <td>{{$obj->doctrantype}}</td>
            <td>{{$obj->docauditno}}</td>
            <td>{{$obj->refsource}}</td>
            <td>{{$obj->reftrantype}}</td>
            <td>{{$obj->refauditno}}</td>
            <td>{{$obj->refamount}}</td>
            <td>{{Carbon\Carbon::parse($obj->allocdate)->format('d/m/Y')}}</td>
            <td>{{$obj->allocamount}}</td>
            <td>{{$obj->recstatus}}</td>
            <td>{{$obj->outamount}}</td>
            <td>{{$obj->paymode}}</td>
            <td>{{$obj->bankcode}}</td>
            <td>{{$obj->reference}}</td>
            <td>{{$obj->cheqdate}}</td>
            <td>{{$obj->suppcode}}</td>
            <td>{{$obj->remarks}}</td>
            <td>{{$obj->lastuser}}</td>
            <td>{{Carbon\Carbon::parse($obj->lastupdate)->format('d/m/Y')}}</td>
            <td>{{$obj->unit}}</td>
            <td>{{$obj->balance}}</td>
            <td>{{$obj->can_alloc}}</td>
        </tr>
    @endforeach
</table>