<table>
    <tr>
        <td>compcode</td>
        <td>source</td>
        <td>trantype</td>
        <td>auditno</td>
        <td>description</td>
        <td>quantity</td>
        <td>amount</td>
        <td>outamt</td>
        <td>taxamt</td>
        <td>mrn</td>
        <td>episno</td>
        <td>paymode</td>
        <td>cardno</td>
        <td>debtortype</td>
        <td>debtorcode</td>
        <td>billno</td>
        <td>lineno_</td>
        <td>billtype</td>
        <td>chgclass</td>
        <td>classlevel</td>
        <td>chggroup</td>
        <td>lastuser</td>
        <td>lastupdate</td>
        <td>invcode</td>
        <td>seqno</td>
        <td>discamt</td>
        <td>docref</td>
        <td>DoctorCode</td>
        <td>taxcode</td>
    </tr>
@foreach ($collection as $obj)
        <tr>
            <td>{{$obj->compcode}}</td>
            <td>{{$obj->source}}</td>
            <td>{{$obj->trantype}}</td>
            <td>{{$obj->auditno}}</td>
            <td>{{$obj->description}}</td>
            <td>{{$obj->quantity}}</td>
            <td>{{$obj->amount}}</td>
            <td>{{$obj->outamt}}</td>
            <td>{{$obj->taxamt}}</td>
            <td>{{$obj->mrn}}</td>
            <td>{{$obj->episno}}</td>
            <td>{{$obj->paymode}}</td>
            <td>{{$obj->cardno}}</td>
            <td>{{$obj->debtortype}}</td>
            <td>{{$obj->debtorcode}}</td>
            <td>{{$obj->billno}}</td>
            <td>{{$obj->lineno_}}</td>
            <td>{{$obj->billtype}}</td>
            <td>{{$obj->chgclass}}</td>
            <td>{{$obj->classlevel}}</td>
            <td>{{$obj->chggroup}}</td>
            <td>{{$obj->lastuser}}</td>
            <td>{{Carbon\Carbon::parse($obj->lastupdate)->format('d/m/Y')}}</td>
            <td>{{$obj->invcode}}</td>
            <td>{{$obj->seqno}}</td>
            <td>{{$obj->discamt}}</td>
            <td>{{$obj->docref}}</td>
            <td></td>
            <td>{{$obj->taxcode}}</td>
        </tr>
    @endforeach
</table>