<table>
    <tr>
        <td>compcode</td>
        <td>mrn</td>
        <td>episno</td>
        <td>epistype</td>
        <td>trxtype</td>
        <td>docref</td>
        <td>trxdate</td>
        <td>chgcode</td>
        <td>counter</td>    
        <td>billcode</td>
        <td>costcd</td>
        <td>revcd</td>
        <td>mmacode</td>
        <td>postdate</td>
        <td>billtype</td>
        <td>doctorcode</td>
        <td>chg_class</td>
        <td>unitprce</td>
        <td>quantity</td>
        <td>amount</td>
        <td>trxtime</td>
        <td>chggroup</td>
        <td>dracccode</td>
        <td>cracccode</td>
        <td>taxamount</td>
        <td>billno</td>
        <td>auditno</td>
        <td>uom</td>
        <td>billtime</td>
        <td>invgroup</td>
        <td>reqdept</td>
        <td>issdept</td>
        <td>lineno_</td>
        <td>billflag</td>
        <td>invcode</td>
        <td>arprocess</td>
        <td>discamt</td>
        <td>disccode</td>
        <td>pkgcode</td>
        <td>splitflag</td>
        <td>taxcode</td>
        <td>MaterialCost</td>
        <td>LabCost</td>
        <td>XrayCost</td>
    </tr>
    @foreach ($collection as $obj)
        <tr>
            <td>{{$obj->compcode}}</td>
            <td>{{$obj->mrn}}</td>
            <td>{{$obj->episno}}</td>
            <td>{{$obj->epistype}}</td>
            <td>{{$obj->trxtype}}</td>
            <td>{{$obj->docref}}</td>
            <td>{{Carbon\Carbon::parse($obj->trxdate)->format('d/m/Y')}}</td>
            <td>{{$obj->chgcode}}</td>
            <td>{{$obj->counter}}</td>
            <td>{{$obj->billcode}}</td>
            <td>{{$obj->costcd}}</td>
            <td>{{$obj->revcd}}</td>
            <td>{{$obj->mmacode}}</td>
            <td>{{Carbon\Carbon::parse($obj->billdate)->format('d/m/Y')}}</td>
            <td>{{$obj->billtype}}</td>
            <td>{{$obj->doctorcode}}</td>
            <td>{{$obj->chg_class}}</td>
            <td>{{$obj->unitprce}}</td>
            <td>{{$obj->quantity}}</td>
            <td>{{$obj->amount}}</td>
            <td>{{$obj->trxtime}}</td>
            <td>{{$obj->chggroup}}</td>
            <td>{{$obj->dracccode}}</td>
            <td>{{$obj->cracccode}}</td>
            <td>{{$obj->taxamount}}</td>
            <td>{{$obj->billno}}</td>
            <td>{{$obj->auditno}}</td>
            <td>{{$obj->uom}}</td>
            <td>{{$obj->billtime}}</td>
            <td>{{$obj->invgroup}}</td>
            <td>{{$obj->reqdept}}</td>
            <td>{{$obj->issdept}}</td>
            <td>{{$obj->lineno_}}</td>
            <td>@if(empty($obj->billflag)){{'no'}}@else{{'yes'}}@endif</td>
            <td>{{$obj->invcode}}</td>
            <td>@if(empty($obj->arprocess)){{'no'}}@else{{'yes'}}@endif</td>
            <td>{{$obj->discamt}}</td>
            <td>{{$obj->disccode}}</td>
            <td>{{$obj->pkgcode}}</td>
            <td>@if(empty($obj->splitflag)){{'no'}}@else{{'yes'}}@endif</td>
            <td>{{$obj->taxcode}}</td>
            <td></td>
            <td></td>            
            <td></td>
        </tr>
    @endforeach
</table>