<table>
    <tr>
      <td>compcode</td>
      <td>source</td>
      <td>trantype</td>
      <td>auditno</td>
      <td>lineno_</td>
      <td>amount</td>
      <td>outamount</td>
      <td>recstatus</td>
      <td>entrydate</td>
      <td>entrytime</td>
      <td>entryuser</td>
      <td>reference</td>
      <td>recptno</td>
      <td>paymode</td>
      <td>tillcode</td>
      <td>tillno</td>
      <td>debtortype</td>
      <td>debtorcode</td>
      <td>payercode</td>
      <td>billdebtor</td>
      <td>remark</td>
      <td>mrn</td>
      <td>episno</td>
      <td>authno</td>
      <td>expdate</td>
      <td>upddate</td>
      <td>upduser</td>
      <td>epistype</td>
      <td>cbflag</td>
      <td>conversion</td>
      <td>payername</td>
      <td>hdrtype</td>
      <td>currency</td>
      <td>rate</td>
      <td>unit</td>
      <td>invno</td>
      <td>BalanceAmt</td>
      <td>ChargeCategory</td>
      <td>ChargeAmt</td>
      <td>DocumentNo</td>
    </tr>
    @foreach ($table as $obj)
        <tr>
            <td>{{$obj->compcode}}</td>
            <td>{{$obj->source}}</td>
            <td>{{$obj->trantype}}</td>
            <td>{{$obj->auditno}}</td>
            <td>{{$obj->lineno_}}</td>
            <td>{{$obj->amount}}</td>
            <td>{{$obj->outamount}}</td>
            <td>{{$obj->recstatus}}</td>
            <td>{{Carbon\Carbon::parse($obj->entrydate)->format('d/m/Y')}}</td>
            <td>{{$obj->entrytime}}</td>
            <td>{{$obj->entryuser}}</td>
            <td>{{$obj->reference}}</td>
            <td>{{$obj->recptno}}</td>
            <td>{{$obj->paymode}}</td>
            <td>{{$obj->tillcode}}</td>
            <td>{{$obj->tillno}}</td>
            <td>{{$obj->debtortype}}</td>
            <td>{{$obj->debtorcode}}</td>
            <td>{{$obj->payercode}}</td>
            <td>{{$obj->billdebtor}}</td>
            <td>{{$obj->remark}}</td>
            <td>{{$obj->mrn}}</td>
            <td>{{$obj->episno}}</td>
            <td>{{$obj->authno}}</td>
            <td>{{Carbon\Carbon::parse($obj->expdate)->format('d/m/Y')}}</td>
            <td>{{Carbon\Carbon::parse($obj->upddate)->format('d/m/Y')}}</td>
            <td>{{$obj->upduser}}</td>
            <td>{{$obj->epistype}}</td>
            <td>@if(empty($obj->cbflag)){{'no'}}@else{{'yes'}}@endif</td>
            <td>@if(empty($obj->conversion)){{'no'}}@else{{'yes'}}@endif</td>
            <td>{{$obj->payername}}</td>
            <td>{{$obj->hdrtype}}</td>
            <td>{{$obj->currency}}</td>
            <td>{{$obj->rate}}</td>
            <td>{{$obj->unit}}</td>
            <td>{{$obj->invno}}</td>
            <td></td>
            <td></td>
            <td></td>
            <td></td>
        </tr>
    @endforeach
</table>