<table>
    <tr>
        <td>compcode</td>
        <td>recno</td>
        <td>lineno_</td>
        <td>pricecode</td>
        <td>itemcode</td>
        <td>uomcode</td>
        <td>qtytag</td>
        <td>unitprice</td>
        <td>amtdisc</td>
        <td>perdisc</td>
        <td>prortdisc</td>
        <td>amtslstax</td>
        <td>perslstax</td>
        <td>netunitprice</td>
        <td>remarks</td>
        <td>expdate</td>
        <td>batchno</td>
        <td>sitemcode</td>
        <td>adduser</td>
        <td>adddate</td>
        <td>upduser</td>
        <td>upddate</td>
        <td>discflg</td>
        <td>discval</td>
        <td>qtyorder</td>
        <td>qtydelivered</td>
        <td>productcat</td>
        <td>draccno</td>
        <td>drccode</td>
        <td>craccno</td>
        <td>crccode</td>
        <td>source</td>
        <td>updtime</td>
        <td>ExpDate</td>
        <td>polineno</td>
        <td>itemmargin</td>
        <td>amount</td>
        <td>Mrn</td>
        <td>EpisNo</td>
        <td>totamount</td>
        <td>taxcode</td>
        <td>TaxClaim</td>
    </tr>
    @foreach ($table as $obj)
        <tr>
            <td>{{$obj->compcode}}</td>
            <td>{{$obj->recno}}</td>
            <td>{{$obj->lineno_}}</td>
            <td>{{$obj->pricecode}}</td>
            <td>{{$obj->itemcode}}</td>
            <td>{{$obj->uomcode}}</td>
            <td>{{$obj->qtytag}}</td>
            <td>{{$obj->unitprice}}</td>
            <td>{{$obj->amtdisc}}</td>
            <td>{{$obj->perdisc}}</td>
            <td>{{$obj->prortdisc}}</td>
            <td>{{$obj->amtslstax}}</td>
            <td>{{$obj->perslstax}}</td>
            <td>{{$obj->netunitprice}}</td>
            <td>{{$obj->remarks}}</td>
            <td>{{Carbon\Carbon::parse($obj->expdate)->format('d/m/Y')}}</td>
            <td>{{$obj->batchno}}</td>
            <td>{{$obj->sitemcode}}</td>
            <td>{{$obj->adduser}}</td>
            <td>{{Carbon\Carbon::parse($obj->adddate)->format('d/m/Y')}}</td>
            <td>{{$obj->upduser}}</td>
            <td>{{Carbon\Carbon::parse($obj->upddate)->format('d/m/Y')}}</td>
            <td>{{$obj->discflg}}</td>
            <td>'no'</td>
            <td>{{$obj->qtyorder}}</td>
            <td>{{$obj->qtydelivered}}</td>
            <td>{{$obj->productcat}}</td>
            <td>{{$obj->draccno}}</td>
            <td>{{$obj->drccode}}</td>
            <td>{{$obj->craccno}}</td>
            <td>{{$obj->crccode}}</td>
            <td>{{$obj->source}}</td>
            <td>{{$obj->updtime}}</td>
            <td></td>
            <td>{{$obj->polineno}}</td>
            <td>{{$obj->itemmargin}}</td>
            <td>{{$obj->amount}}</td>
            <td></td>
            <td></td>
            <td>{{$obj->totamount}}</td>
            <td>{{$obj->taxcode}}</td>
            <td></td>
        </tr>
    @endforeach
</table>