<table>
    <tr>
        <td>compcode</td>
        <td>recno</td>
        <td>lineno_</td>
        <td>itemcode</td>
        <td>uomcode</td>
        <td>txnqty</td>
        <td>netprice</td>
        <td>adduser</td>
        <td>adddate</td>
        <td>upduser</td>
        <td>upddate</td>
        <td>productcat</td>
        <td>draccno</td>
        <td>drccode</td>
        <td>craccno</td>
        <td>crccode</td>
        <td>issdept</td>
        <td>reqdept</td>
        <td>saleamt</td>
        <td>trantype</td>
        <td>trandate</td>
        <td>trxaudno</td>
        <td>mrn</td>
        <td>episno</td>
        <td>updtime</td>
        <td>expdate</td>
        <td>batchno</td>
        <td>amount</td>
        <td>Units</td>
        <td>DateInt</td>
    </tr>
    @foreach ($table as $obj)
        <tr>
            <td>{{$obj->compcode}}</td>
            <td>{{$obj->recno}}</td>
            <td>{{$obj->lineno_}}</td>
            <td>{{$obj->itemcode}}</td>
            <td>{{$obj->uomcode}}</td>
            <td>{{$obj->txnqty}}</td>
            <td>{{$obj->netprice}}</td>
            <td>{{$obj->adduser}}</td>
            <td>{{Carbon\Carbon::parse($obj->adddate)->format('d/m/Y')}}</td>
            <td>{{$obj->upduser}}</td>
            <td>{{Carbon\Carbon::parse($obj->upddate)->format('d/m/Y')}}</td>
            <td>{{$obj->productcat}}</td>
            <td>{{$obj->draccno}}</td>
            <td>{{$obj->drccode}}</td>
            <td>{{$obj->craccno}}</td>
            <td>{{$obj->crccode}}</td>
            <td>{{$obj->issdept}}</td>
            <td>{{$obj->reqdept}}</td>
            <td>{{$obj->saleamt}}</td>
            <td>{{$obj->trantype}}</td>
            <td>{{Carbon\Carbon::parse($obj->trandate)->format('d/m/Y')}}</td>
            <td>{{$obj->trxaudno}}</td>
            <td>{{$obj->mrn}}</td>
            <td>{{$obj->episno}}</td>
            <td>{{$obj->updtime}}</td>
            <td>{{Carbon\Carbon::parse($obj->expdate)->format('d/m/Y')}}</td>
            <td>{{$obj->batchno}}</td>
            <td>{{$obj->amount}}</td>
            <td>{{$obj->idno}}</td>
            <td></td>
            <td></td>
        </tr>
    @endforeach
</table>