<table>
    <tr>
        <td>compcode</td>
        <td>recno</td>
        <td>lineno_</td>
        <td>itemcode</td>
        <td>uomcode</td>
        <td>txnqty</td>
        <td>netprice</td>
        <td>adduser</td>
        <td>adddate</td>
        <td>upduser</td>
        <td>upddate</td>
        <td>productcat</td>
        <td>draccno</td>
        <td>drccode</td>
        <td>craccno</td>
        <td>crccode</td>
        <td>updtime</td>
        <td>expdate</td>
        <td>remarks</td>
        <td>qtyonhand</td>
        <td>batchno</td>
        <td>amount</td>
    </tr>
    @foreach ($collection as $obj)
        <tr>
            <td>compcode</td>
            <td>recno</td>
            <td>lineno_</td>
            <td>itemcode</td>
            <td>uomcode</td>
            <td>txnqty</td>
            <td>netprice</td>
            <td>adduser</td>
            <td>{{Carbon\Carbon::parse($obj->adddate)->format('d/m/Y')}}</td>
            <td>upduser</td>
            <td>{{Carbon\Carbon::parse($obj->upddate)->format('d/m/Y')}}</td>
            <td>productcat</td>
            <td>draccno</td>
            <td>drccode</td>
            <td>craccno</td>
            <td>crccode</td>
            <td>updtime</td>
            <td>{{Carbon\Carbon::parse($obj->expdate)->format('d/m/Y')}}</td>
            <td>remarks</td>
            <td>qtyonhand</td>
            <td>batchno</td>
            <td>amount</td>
        </tr>
    @endforeach
</table>