<table>
    <tr>
        <td>compcode</td>
        <td>recno</td>
        <td>lineno_</td>
        <td>itemcode</td>
        <td>uomcode</td>
        <td>txnqty</td>
        <td>netprice</td>
        <td>adduser</td>
        <td>adddate</td>
        <td>upduser</td>
        <td>upddate</td>
        <td>productcat</td>
        <td>draccno</td>
        <td>drccode</td>
        <td>craccno</td>
        <td>crccode</td>
        <td>updtime</td>
        <td>expdate</td>
        <td>remarks</td>
        <td>qtyonhand</td>
        <td>batchno</td>
        <td>amount</td>
        <td>pouom</td>
        <td>trantype</td>
    </tr>
    @foreach ($collection as $obj)
        <tr>
            <td>{{$obj->compcode}}</td>
            <td>{{$obj->recno}}</td>
            <td>{{$obj->lineno_}}</td>
            <td>{{$obj->itemcode}}</td>
            <td>{{$obj->uomcode}}</td>
            <td>{{$obj->txnqty}}</td>
            <td>{{$obj->netprice}}</td>
            <td>{{$obj->adduser}}</td>
            @if(empty($obj->adddate))
            <td></td>
            @else
            <td>{{Carbon\Carbon::parse($obj->adddate)->format('d/m/Y')}}</td>
            @endif
            <td>{{$obj->upduser}}</td>
            @if(empty($obj->upddate))
            <td></td>
            @else
            <td>{{Carbon\Carbon::parse($obj->upddate)->format('d/m/Y')}}</td>
            @endif
            <td>{{$obj->productcat}}</td>
            <td>{{$obj->draccno}}</td>
            <td>{{$obj->drccode}}</td>
            <td>{{$obj->craccno}}</td>
            <td>{{$obj->crccode}}</td>
            <td>{{$obj->updtime}}</td>
            @if(empty($obj->expdate))
            <td></td>
            @else
            <td>{{Carbon\Carbon::parse($obj->expdate)->format('d/m/Y')}}</td>
            @endif
            <td>{{$obj->remarks}}</td>
            <td>{{$obj->qtyonhand}}</td>
            <td>{{$obj->batchno}}</td>
            <td>{{$obj->amount}}</td>
            <td>{{$obj->pouom}}</td>
            <td>{{$obj->trantype}}</td>
        </tr>
    @endforeach
</table>