<table>
    <tr>
        <td>compcode</td>
        <td>srcdept</td>
        <td>phycntdate</td>
        <td>phycnttime</td>
        <td>respersonid</td>
        <td>remarks</td>
        <td>recstatus</td>
        <td>adduser</td>
        <td>adddate</td>
        <td>upduser</td>
        <td>upddate</td>
        <td>recno</td>
        <td>rackno</td>
        <td>subcatcode</td>
        <td>docno</td>
        <td>frzdate</td>
        <td>frztime</td>
        <td>itemfrom</td>
        <td>itemto</td>
        <td>computerid</td>
    </tr>
    @foreach ($table as $obj)
        <tr>
            <td>{{$obj->compcode}}</td>
            <td>{{$obj->srcdept}}</td>
            <td>{{Carbon\Carbon::parse($obj->phycntdate)->format('d/m/Y')}}</td>
            <td>{{$obj->phycnttime}}</td>
            <td>{{$obj->respersonid}}</td>
            <td>{{$obj->remarks}}</td>
            <td>{{$obj->recstatus}}</td>
            <td>{{$obj->adduser}}</td>
            <td>{{Carbon\Carbon::parse($obj->adddate)->format('d/m/Y')}}</td>
            <td>{{$obj->upduser}}</td>
            <td>{{Carbon\Carbon::parse($obj->upddate)->format('d/m/Y')}}</td>
            <td>{{$obj->recno}}</td>
            <td>{{$obj->rackno}}</td>
            <td>{{$obj->subcatcode}}</td>
            <td>{{$obj->docno}}</td>
            <td>{{Carbon\Carbon::parse($obj->frzdate)->format('d/m/Y')}}</td>
            <td>{{$obj->frztime}}</td>
            <td>{{$obj->itemfrom}}</td>
            <td>{{$obj->itemto}}</td>
            <td>{{$obj->computerid}}</td>
        </tr>
    @endforeach
</table>