<table>
    <tr>
        <td>compcode</td>
        <td>itemcode</td>
        <td>groupcode</td>
        <td>productcat</td>
        <td>description</td>
        <td>uomcode</td>
        <td>avgcost</td>
        <td>actavgcost</td>
        <td>currprice</td>
        <td>qtyonhand</td>
        <td>bonqty</td>
        <td>suppcode</td>
        <td>rpkitem</td>
        <td>minqty</td>
        <td>maxqty</td>
        <td>reordlevel</td>
        <td>reordqty</td>
        <td>adduser</td>
        <td>adddate</td>
        <td>upduser</td>
        <td>upddate</td>
        <td>recstatus</td>
        <td>chgflag</td>
        <td>subcatcode</td>
        <td>expdtflg</td>
        <td>mstore</td>
        <td>costmargin</td>
        <td>pouom</td>
        <td>reuse</td>
        <td>trqty</td>
        <td>deactivedate</td>
        <td>tagging</td>
        <td>itemtype</td>
        <td>generic</td>
        <td>SupplierItem</td>
        <td>unit</td>
        <td>BarCode</td>
        <td>CurrAvgCost</td>
        <td>Consignment</td>
        <td>TaxCode</td>
    </tr>
    @foreach ($table as $obj)
        <tr>
            <td>{{$obj->compcode}}</td>
            <td>{{$obj->itemcode}}</td>
            <td>{{$obj->groupcode}}</td>
            <td>{{$obj->productcat}}</td>
            <td>{{$obj->description}}</td>
            <td>{{$obj->uomcode}}</td>
            <td>{{$obj->avgcost}}</td>
            <td>{{$obj->actavgcost}}</td>
            <td>{{$obj->currprice}}</td>
            <td>{{$obj->qtyonhand}}</td>
            <td>{{$obj->bonqty}}</td>
            <td>{{$obj->suppcode}}</td>
            <td>@if(empty($obj->rpkitem)){{'no'}}@else{{'yes'}}@endif</td>
            <td>{{$obj->minqty}}</td>
            <td>{{$obj->maxqty}}</td>
            <td>{{$obj->reordlevel}}</td>
            <td>{{$obj->reordqty}}</td>
            <td>{{$obj->adduser}}</td>
            <td>{{Carbon\Carbon::parse($obj->adddate)->format('d/m/Y')}}</td>
            <td>{{$obj->upduser}}</td>
            <td>{{Carbon\Carbon::parse($obj->upddate)->format('d/m/Y')}}</td>
            <td>@if($obj->recstatus == 'ACTIVE'){{'yes'}}@else{{'no'}}@endif</td>
            <td>@if(empty($obj->chgflag)){{'no'}}@else{{'yes'}}@endif</td>
            <td>{{$obj->subcatcode}}</td>
            <td>@if(empty($obj->expdtflg)){{'no'}}@else{{'yes'}}@endif</td>
            <td>{{$obj->mstore}}</td>
            <td>{{$obj->costmargin}}</td>
            <td>{{$obj->pouom}}</td>
            <td>@if(empty($obj->reuse)){{'no'}}@else{{'yes'}}@endif</td>
            <td>{{$obj->trqty}}</td>
            <td>{{Carbon\Carbon::parse($obj->deactivedate)->format('d/m/Y')}}</td>
            <td>{{$obj->tagging}}</td>
            <td>{{$obj->itemtype}}</td>
            <td>{{$obj->generic}}</td>
            <td></td>
            <td>{{$obj->unit}}</td>
            <td></td>
            <td></td>
            <td>@if(empty($obj->Consignment)){{'no'}}@else{{'yes'}}@endif</td>
            <td>{{$obj->TaxCode}}</td>
        </tr>
    @endforeach
</table>