<table>
    <tr>
        <td>compcode</td>
        <td>deptcode</td>
        <td>itemcode</td>
        <td>uomcode</td>
        <td>bincode</td>
        <td>rackno</td>
        <td>year</td>
        <td>openbalqty</td>
        <td>openbalval</td>
        <td>netmvqty1</td>
        <td>netmvqty2</td>
        <td>netmvqty3</td>
        <td>netmvqty4</td>
        <td>netmvqty5</td>
        <td>netmvqty6</td>
        <td>netmvqty7</td>
        <td>netmvqty8</td>
        <td>netmvqty9</td>
        <td>netmvqty10</td>
        <td>netmvqty11</td>
        <td>netmvqty12</td>
        <td>netmvval1</td>
        <td>netmvval2</td>
        <td>netmvval3</td>
        <td>netmvval4</td>
        <td>netmvval5</td>
        <td>netmvval6</td>
        <td>netmvval7</td>
        <td>netmvval8</td>
        <td>netmvval9</td>
        <td>netmvval10</td>
        <td>netmvval11</td>
        <td>netmvval12</td>
        <td>stocktxntype</td>
        <td>disptype</td>
        <td>qtyonhand</td>
        <td>minqty</td>
        <td>maxqty</td>
        <td>reordlevel</td>
        <td>reordqty</td>
        <td>lastissdate</td>
        <td>frozen</td>
        <td>adduser</td>
        <td>adddate</td>
        <td>upduser</td>
        <td>upddate</td>
        <td>cntdocno</td>
        <td>fix_uom</td>
        <td>locavgcs</td>
        <td>lstfrzdt</td>
        <td>lstfrztm</td>
        <td>frzqty</td>
        <td>recstatus</td>
        <td>deluser</td>
        <td>deldate</td>
        <td>computerid</td>
        <td>ipaddress</td>
        <td>lastcomputerid</td>
        <td>lastipaddress</td>
        <td>unit</td>
    </tr>
    @foreach ($table as $obj)
        <tr>
            <td>{{$obj->compcode}}</td>
            <td>{{$obj->deptcode}}</td>
            <td>{{$obj->itemcode}}</td>
            <td>{{$obj->uomcode}}</td>
            <td>{{$obj->bincode}}</td>
            <td>{{$obj->rackno}}</td>
            <td>{{$obj->year}}</td>
            <td>{{$obj->openbalqty}}</td>
            <td>{{$obj->openbalval}}</td>
            <td>{{$obj->netmvqty1}}</td>
            <td>{{$obj->netmvqty2}}</td>
            <td>{{$obj->netmvqty3}}</td>
            <td>{{$obj->netmvqty4}}</td>
            <td>{{$obj->netmvqty5}}</td>
            <td>{{$obj->netmvqty6}}</td>
            <td>{{$obj->netmvqty7}}</td>
            <td>{{$obj->netmvqty8}}</td>
            <td>{{$obj->netmvqty9}}</td>
            <td>{{$obj->netmvqty10}}</td>
            <td>{{$obj->netmvqty11}}</td>
            <td>{{$obj->netmvqty12}}</td>
            <td>{{$obj->netmvval1}}</td>
            <td>{{$obj->netmvval2}}</td>
            <td>{{$obj->netmvval3}}</td>
            <td>{{$obj->netmvval4}}</td>
            <td>{{$obj->netmvval5}}</td>
            <td>{{$obj->netmvval6}}</td>
            <td>{{$obj->netmvval7}}</td>
            <td>{{$obj->netmvval8}}</td>
            <td>{{$obj->netmvval9}}</td>
            <td>{{$obj->netmvval10}}</td>
            <td>{{$obj->netmvval11}}</td>
            <td>{{$obj->netmvval12}}</td>
            <td>{{$obj->stocktxntype}}</td>
            <td>{{$obj->disptype}}</td>
            <td>{{$obj->qtyonhand}}</td>
            <td>{{$obj->minqty}}</td>
            <td>{{$obj->maxqty}}</td>
            <td>{{$obj->reordlevel}}</td>
            <td>{{$obj->reordqty}}</td>
            <td>{{Carbon\Carbon::parse($obj->lastissdate)->format('d/m/Y')}}</td>
            <td>{{$obj->frozen}}</td>
            <td>{{$obj->adduser}}</td>
            <td>{{Carbon\Carbon::parse($obj->adddate)->format('d/m/Y')}}</td>
            <td>{{$obj->upduser}}</td>
            <td>{{Carbon\Carbon::parse($obj->upddate)->format('d/m/Y')}}</td>
            <td>{{$obj->cntdocno}}</td>
            <td>{{$obj->fix_uom}}</td>
            <td>{{$obj->locavgcs}}</td>
            <td>{{$obj->lstfrzdt}}</td>
            <td>{{$obj->lstfrztm}}</td>
            <td>{{$obj->frzqty}}</td>
            <td>{{$obj->recstatus}}</td>
            <td>{{$obj->deluser}}</td>
            <td>{{Carbon\Carbon::parse($obj->deldate)->format('d/m/Y')}}</td>
            <td>{{$obj->computerid}}</td>
            <td>{{$obj->ipaddress}}</td>
            <td>{{$obj->lastcomputerid}}</td>
            <td>{{$obj->lastipaddress}}</td>
            <td>{{$obj->unit}}</td>
        </tr>
    @endforeach
</table>